language: node_js

node_js:
  - '8'

cache: npm

before_script:
  - npm run build-storybook

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: storybook-static
  repo: marshmallow-insurance/smores-react
  target_branch: gh-pages
  on:
    branch: master
