language: node_js

node_js:
  - '8'

cache: yarn

before_script:
  - yarn run build-storybook

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: storybook-static
  repo: marshmallow-insurance/smores-react
  target_branch: gh-pages
  on:
    branch: master
