import React, { FocusEvent } from 'react';
import { Icons } from 'Icon/iconsList';
import { BaseValueType, DisplayType, IconPosition } from './types';
type RadioItemProps = {
    name: string;
    visual?: string;
    icon?: Icons;
    iconPosition?: IconPosition;
    value: BaseValueType;
    label: string;
    checked: boolean;
    onChange: (value: BaseValueType) => void;
    onBlur?: (e: FocusEvent<HTMLInputElement>) => void;
    displayType: DisplayType;
    isError: boolean;
    fallbackStyle?: boolean;
    bodyCopy?: string;
};
export declare const RadioItem: React.ForwardRefExoticComponent<RadioItemProps & React.RefAttributes<HTMLInputElement>>;
export {};
