version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'
    default_assignees:
      - 'ellajay'
      - 'habin-isa'
      - 'fleonard'
      - 'trcywu'
    default_reviewers:
      - 'ellajay'
      - 'habin-isa'
      - 'fleonard'
      - 'trcywu'
    automerged_updates:
      - match:
          dependency_type: 'development'
          update_type: 'in_range'
      - match:
          dependency_type: 'production'
          update_type: 'in_range'
