name: Approve and Merge Dependabot PRs

on:
  pull_request_target:
    branches: [ main ]

jobs:
  auto-merge-dependabot:
    uses: marshmallow-insurance/campfire/.github/workflows/shared-auto-merge-dependabot.yml@main
    secrets: inherit
